MyFilterChain:
    - name: butterworth-lowpass
      type: rosneuro_filters/ButterworthFilterFloat
      params: 
        samplerate: 256
        type: lowpass
        order: 2
        cutoff: 40
    - name: butterworth-highpass
      type: rosneuro_filters/ButterworthFilterFloat
      params: 
        samplerate: 256
        type: highpass
        order: 2
        cutoff: 1
    - name: car
      type: rosneuro_filters/CarFilterFloat
